import { Pause, Play, SkipBack, SkipForward, Volume2 } from 'lucide-react';
import { useSillage } from '@/lib/store';
import { Slider } from '@/components/ui/slider';
import { useEffect, useRef, useState } from 'react';
import { formatDuration } from '@/lib/utils';

export function Player() {
  const { currentlyPlaying, isPlaying, togglePlay, setPlaying, library } = useSillage();
  const audio = useRef<HTMLAudioElement>(null); const [current,setCurrent]=useState(0); const [volume,setVolume]=useState(75); const [failure,setFailure]=useState<string|null>(null);
  useEffect(()=>{ const player=audio.current;if(!player)return; player.volume=volume/100; },[volume]);
  useEffect(()=>{const player=audio.current;if(!player)return;setCurrent(0);setFailure(null);if(!currentlyPlaying?.previewUrl&&!currentlyPlaying?.streamUrl){setFailure('Aucune source audio disponible pour ce titre.');return;}player.src=currentlyPlaying.streamUrl||currentlyPlaying.previewUrl||'';if(isPlaying)player.play().catch(()=>setFailure('La lecture a été bloquée ou le média est indisponible.'));return()=>{player.pause();player.removeAttribute('src');player.load();};},[currentlyPlaying]);
  useEffect(()=>{const player=audio.current;if(!player)return;if(isPlaying)player.play().catch(()=>setFailure('La lecture a été bloquée par le navigateur.'));else player.pause();},[isPlaying]);
  const move=(step:number)=>{if(!currentlyPlaying)return;const index=library.findIndex(x=>x.id===currentlyPlaying.id);const next=library[index+step];if(next)setPlaying(next);};
  if(!currentlyPlaying)return <div className="h-24 bg-card border-t border-border flex items-center justify-center px-6"><p className="text-muted-foreground text-sm">Sélectionnez un morceau avec une source audio pour l’écouter</p></div>;
  const duration=Number.isFinite(audio.current?.duration)?audio.current!.duration:(currentlyPlaying.duration||0);
  return <div className="h-24 bg-card border-t border-border flex items-center justify-between px-6 z-50"><audio ref={audio} preload="metadata" onTimeUpdate={e=>setCurrent(e.currentTarget.currentTime)} onEnded={()=>setPlaying(currentlyPlaying,false)} onError={()=>{setFailure('Impossible de charger cet audio.');setPlaying(currentlyPlaying,false);}}/><div className="flex items-center gap-4 w-1/3 min-w-0"><img src={currentlyPlaying.cover || '/favicon.svg'} alt="" className="w-14 h-14 rounded object-cover bg-muted"/><div className="min-w-0"><h4 className="font-medium text-foreground truncate">{currentlyPlaying.title}</h4><p className="text-xs text-muted-foreground truncate">{currentlyPlaying.artist}</p>{failure&&<p className="text-[10px] text-destructive truncate">{failure}</p>}</div></div><div className="flex flex-col items-center gap-2 w-1/3 max-w-[500px]"><div className="flex items-center gap-6"><button onClick={()=>move(-1)} disabled={!library.length} className="text-muted-foreground disabled:opacity-30"><SkipBack className="w-5 h-5 fill-current"/></button><button className="w-10 h-10 flex items-center justify-center rounded-full bg-primary text-primary-foreground" onClick={togglePlay}>{isPlaying?<Pause className="w-5 h-5 fill-current"/>:<Play className="w-5 h-5 fill-current ml-1"/>}</button><button onClick={()=>move(1)} disabled={!library.length} className="text-muted-foreground disabled:opacity-30"><SkipForward className="w-5 h-5 fill-current"/></button></div><div className="w-full flex items-center gap-3"><span className="text-[10px] text-muted-foreground w-8 text-right font-mono">{formatDuration(current)}</span><Slider value={[duration?current/duration*100:0]} max={100} step={0.1} className="w-full" onValueChange={v=>{if(audio.current&&duration)audio.current.currentTime=duration*v[0]/100;}}/><span className="text-[10px] text-muted-foreground w-8 font-mono">{formatDuration(duration)}</span></div></div><div className="flex items-center justify-end gap-3 w-1/3"><Volume2 className="w-5 h-5 text-muted-foreground"/><Slider value={[volume]} max={100} step={1} className="w-24" onValueChange={v=>setVolume(v[0])}/></div></div>;
}