import { Track, Playlist, Folder, Moment, Proposal } from './types';

export const MARIAGE_UNIVERSEL_CATEGORIES = [
  "Accueil & Découverte",
  "Cérémonie Laïque",
  "Cérémonie Religieuse",
  "Cocktail Élégant",
  "Entrée des Mariés",
  "Dîner Convivial",
  "Ouverture du Bal",
  "Dancefloor - Généraliste",
  "Dancefloor - Électronique",
  "Fin de Nuit"
];

const COVERS = [
  "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=400&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?q=80&w=400&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1619983081563-430f63602796?q=80&w=400&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=400&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=400&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1493225457124-a1a2a5faeb3e?q=80&w=400&auto=format&fit=crop",
];

export const MOCK_LIBRARY: Track[] = [
  {
    id: "t1",
    title: "At Last",
    artist: "Etta James",
    album: "At Last!",
    cover: COVERS[0],
    duration: 180,
    year: 1960,
    genre: "Soul",
    bpm: 90,
    key: "F Major",
    energy: 3,
    moods: ["Romantique", "Classique", "Intemporel"],
    momentTags: ["Cérémonie", "Ouverture du Bal"],
    colorHue: 45
  },
  {
    id: "t2",
    title: "You've Got The Love",
    artist: "Florence + The Machine",
    album: "Lungs",
    cover: COVERS[1],
    duration: 168,
    year: 2009,
    genre: "Indie Pop",
    bpm: 110,
    key: "A Minor",
    energy: 8,
    moods: ["Épique", "Joyeux", "Énergique"],
    momentTags: ["Entrée des Mariés", "Dancefloor - Généraliste"],
    colorHue: 320
  },
  {
    id: "t3",
    title: "L-O-V-E",
    artist: "Nat King Cole",
    album: "L-O-V-E",
    cover: COVERS[2],
    duration: 154,
    year: 1965,
    genre: "Jazz",
    bpm: 155,
    key: "G Major",
    energy: 5,
    moods: ["Léger", "Swing", "Romantique"],
    momentTags: ["Cocktail", "Dîner"],
    colorHue: 20
  },
  {
    id: "t4",
    title: "I Feel Love",
    artist: "Donna Summer",
    album: "I Remember Yesterday",
    cover: COVERS[3],
    duration: 355,
    year: 1977,
    genre: "Disco",
    bpm: 126,
    key: "C Minor",
    energy: 9,
    moods: ["Électrique", "Hypnotique"],
    momentTags: ["Dancefloor - Électronique", "Bal"],
    colorHue: 280
  },
  {
    id: "t5",
    title: "Can't Help Falling in Love",
    artist: "Elvis Presley",
    album: "Blue Hawaii",
    cover: COVERS[4],
    duration: 182,
    year: 1961,
    genre: "Pop",
    bpm: 68,
    key: "D Major",
    energy: 2,
    moods: ["Tendre", "Doux", "Romantique"],
    momentTags: ["Cérémonie", "Dernière chanson"],
    colorHue: 210
  },
  {
    id: "t6",
    title: "September",
    artist: "Earth, Wind & Fire",
    album: "The Best of Earth, Wind & Fire, Vol. 1",
    cover: COVERS[5],
    duration: 215,
    year: 1978,
    genre: "Disco / Funk",
    bpm: 125,
    key: "A Major",
    energy: 9,
    moods: ["Joyeux", "Célébration", "Groove"],
    momentTags: ["Bal", "Dancefloor - Généraliste"],
    colorHue: 35
  },
  {
    id: "t7",
    title: "Music Sounds Better With You",
    artist: "Stardust",
    album: "Music Sounds Better With You",
    cover: COVERS[0],
    duration: 402,
    year: 1998,
    genre: "French Touch",
    bpm: 124,
    key: "A Minor",
    energy: 8,
    moods: ["Nostalgique", "Euphorique"],
    momentTags: ["Dancefloor - Électronique"],
    colorHue: 190
  },
  {
    id: "t8",
    title: "La Vie En Rose",
    artist: "Edith Piaf",
    album: "Chansons Parisiennes",
    cover: COVERS[1],
    duration: 185,
    year: 1947,
    genre: "Chanson",
    bpm: 78,
    key: "C Major",
    energy: 2,
    moods: ["Vintage", "Parisien", "Romantique"],
    momentTags: ["Accueil", "Dîner"],
    colorHue: 340
  },
  {
    id: "t9",
    title: "Let's Stay Together",
    artist: "Al Green",
    album: "Let's Stay Together",
    cover: COVERS[2],
    duration: 198,
    year: 1972,
    genre: "Soul",
    bpm: 102,
    key: "F Major",
    energy: 4,
    moods: ["Groove", "Chaleureux"],
    momentTags: ["Cocktail", "Dîner"],
    colorHue: 15
  },
  {
    id: "t10",
    title: "Daft Punk",
    artist: "One More Time",
    album: "Discovery",
    cover: COVERS[3],
    duration: 320,
    year: 2000,
    genre: "Electronic",
    bpm: 122,
    key: "D Major",
    energy: 9,
    moods: ["Célébration", "Électrique"],
    momentTags: ["Bal", "Dancefloor - Électronique"],
    colorHue: 250
  },
  {
    id: "t11",
    title: "Your Song",
    artist: "Elton John",
    album: "Elton John",
    cover: COVERS[4],
    duration: 243,
    year: 1970,
    genre: "Pop",
    bpm: 128,
    key: "Eb Major",
    energy: 3,
    moods: ["Tendre", "Émouvant"],
    momentTags: ["Cérémonie", "Ouverture du Bal"],
    colorHue: 40
  },
  {
    id: "t12",
    title: "Gimme! Gimme! Gimme!",
    artist: "ABBA",
    album: "Voulez-Vous",
    cover: COVERS[5],
    duration: 292,
    year: 1979,
    genre: "Disco",
    bpm: 120,
    key: "D Minor",
    energy: 8,
    moods: ["Festif", "Iconique"],
    momentTags: ["Dancefloor - Généraliste", "Bal"],
    colorHue: 220
  },
  {
    id: "t13",
    title: "Fly Me To The Moon",
    artist: "Frank Sinatra",
    album: "It Might as Well Be Swing",
    cover: COVERS[0],
    duration: 147,
    year: 1964,
    genre: "Jazz",
    bpm: 119,
    key: "C Major",
    energy: 5,
    moods: ["Swing", "Classe"],
    momentTags: ["Cocktail", "Dîner"],
    colorHue: 25
  },
  {
    id: "t14",
    title: "Crazy In Love",
    artist: "Beyoncé ft. Jay-Z",
    album: "Dangerously In Love",
    cover: COVERS[1],
    duration: 236,
    year: 2003,
    genre: "R&B",
    bpm: 99,
    key: "D Minor",
    energy: 9,
    moods: ["Confiant", "Puissant"],
    momentTags: ["Dancefloor - Généraliste"],
    colorHue: 50
  },
  {
    id: "t15",
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "Divide",
    cover: COVERS[2],
    duration: 263,
    year: 2017,
    genre: "Pop",
    bpm: 95,
    key: "Ab Major",
    energy: 4,
    moods: ["Romantique", "Moderne"],
    momentTags: ["Ouverture du Bal"],
    colorHue: 200
  },
  {
    id: "t16",
    title: "Can't Stop The Feeling!",
    artist: "Justin Timberlake",
    album: "Trolls OST",
    cover: COVERS[3],
    duration: 236,
    year: 2016,
    genre: "Pop",
    bpm: 113,
    key: "C Major",
    energy: 8,
    moods: ["Joyeux", "Solaire"],
    momentTags: ["Cocktail", "Bal"],
    colorHue: 45
  },
  {
    id: "t17",
    title: "Marry You",
    artist: "Bruno Mars",
    album: "Doo-Wops & Hooligans",
    cover: COVERS[4],
    duration: 230,
    year: 2010,
    genre: "Pop",
    bpm: 145,
    key: "F Major",
    energy: 7,
    moods: ["Enjoué", "Optimiste"],
    momentTags: ["Entrée des Mariés"],
    colorHue: 15
  },
  {
    id: "t18",
    title: "Don't Stop Me Now",
    artist: "Queen",
    album: "Jazz",
    cover: COVERS[5],
    duration: 209,
    year: 1978,
    genre: "Rock",
    bpm: 156,
    key: "F Major",
    energy: 9,
    moods: ["Épique", "Explosif"],
    momentTags: ["Dancefloor - Généraliste"],
    colorHue: 350
  },
  {
    id: "t19",
    title: "A Sky Full of Stars",
    artist: "Coldplay",
    album: "Ghost Stories",
    cover: COVERS[0],
    duration: 268,
    year: 2014,
    genre: "Pop Rock / EDM",
    bpm: 125,
    key: "Gb Major",
    energy: 8,
    moods: ["Euphorique", "Spatial"],
    momentTags: ["Bal", "Dancefloor - Généraliste"],
    colorHue: 230
  },
  {
    id: "t20",
    title: "Just The Way You Are",
    artist: "Billy Joel",
    album: "The Stranger",
    cover: COVERS[1],
    duration: 290,
    year: 1977,
    genre: "Soft Rock",
    bpm: 72,
    key: "D Major",
    energy: 4,
    moods: ["Doux", "Sincère"],
    momentTags: ["Dîner", "Accueil"],
    colorHue: 30
  },
  {
    id: "t21",
    title: "Midnight City",
    artist: "M83",
    album: "Hurry Up, We're Dreaming",
    cover: COVERS[2],
    duration: 243,
    year: 2011,
    genre: "Synth-Pop",
    bpm: 105,
    key: "B Minor",
    energy: 8,
    moods: ["Nocturne", "Épique"],
    momentTags: ["Dancefloor - Électronique", "Bal"],
    colorHue: 280
  },
  {
    id: "t22",
    title: "Dancing Queen",
    artist: "ABBA",
    album: "Arrival",
    cover: COVERS[3],
    duration: 231,
    year: 1976,
    genre: "Disco",
    bpm: 100,
    key: "A Major",
    energy: 7,
    moods: ["Iconique", "Joyeux"],
    momentTags: ["Bal", "Dancefloor - Généraliste"],
    colorHue: 50
  },
  {
    id: "t23",
    title: "Shallow",
    artist: "Lady Gaga & Bradley Cooper",
    album: "A Star Is Born",
    cover: COVERS[4],
    duration: 215,
    year: 2018,
    genre: "Pop Rock",
    bpm: 96,
    key: "G Major",
    energy: 6,
    moods: ["Dramatique", "Intense"],
    momentTags: ["Cérémonie"],
    colorHue: 35
  },
  {
    id: "t24",
    title: "Levels",
    artist: "Avicii",
    album: "Levels",
    cover: COVERS[5],
    duration: 199,
    year: 2011,
    genre: "EDM",
    bpm: 126,
    key: "C# Minor",
    energy: 9,
    moods: ["Énergique", "Festival"],
    momentTags: ["Dancefloor - Électronique"],
    colorHue: 190
  },
  {
    id: "t25",
    title: "Stand By Me",
    artist: "Ben E. King",
    album: "Don't Play That Song!",
    cover: COVERS[0],
    duration: 173,
    year: 1961,
    genre: "R&B / Soul",
    bpm: 118,
    key: "A Major",
    energy: 4,
    moods: ["Intemporel", "Fraternel"],
    momentTags: ["Cérémonie", "Dernière chanson"],
    colorHue: 25
  },
  {
    id: "t26",
    title: "I Wanna Dance with Somebody",
    artist: "Whitney Houston",
    album: "Whitney",
    cover: COVERS[1],
    duration: 291,
    year: 1987,
    genre: "Pop",
    bpm: 119,
    key: "Gb Major",
    energy: 9,
    moods: ["Joyeux", "Explosif"],
    momentTags: ["Bal", "Dancefloor - Généraliste"],
    colorHue: 330
  },
  {
    id: "t27",
    title: "Praise You",
    artist: "Fatboy Slim",
    album: "You've Come a Long Way, Baby",
    cover: COVERS[2],
    duration: 324,
    year: 1998,
    genre: "Electronic",
    bpm: 110,
    key: "Gb Major",
    energy: 8,
    moods: ["Funky", "Feel Good"],
    momentTags: ["Dancefloor - Électronique", "Cocktail"],
    colorHue: 45
  },
  {
    id: "t28",
    title: "Isn't She Lovely",
    artist: "Stevie Wonder",
    album: "Songs in the Key of Life",
    cover: COVERS[3],
    duration: 393,
    year: 1976,
    genre: "Soul",
    bpm: 119,
    key: "E Major",
    energy: 6,
    moods: ["Affectueux", "Joyeux"],
    momentTags: ["Cocktail", "Accueil"],
    colorHue: 60
  },
  {
    id: "t29",
    title: "Wake Me Up Before You Go-Go",
    artist: "Wham!",
    album: "Make It Big",
    cover: COVERS[4],
    duration: 233,
    year: 1984,
    genre: "Pop",
    bpm: 163,
    key: "C Major",
    energy: 8,
    moods: ["Enjoué", "Vintage"],
    momentTags: ["Dancefloor - Généraliste"],
    colorHue: 10
  },
  {
    id: "t30",
    title: "Titanium",
    artist: "David Guetta ft. Sia",
    album: "Nothing but the Beat",
    cover: COVERS[5],
    duration: 245,
    year: 2011,
    genre: "EDM",
    bpm: 126,
    key: "Eb Major",
    energy: 9,
    moods: ["Puissant", "Hymne"],
    momentTags: ["Dancefloor - Électronique"],
    colorHue: 210
  },
  {
    id: "t31",
    title: "Love On Top",
    artist: "Beyoncé",
    album: "4",
    cover: COVERS[0],
    duration: 267,
    year: 2011,
    genre: "R&B / Pop",
    bpm: 94,
    key: "C Major",
    energy: 8,
    moods: ["Radieux", "Ascensionnel"],
    momentTags: ["Cocktail", "Bal"],
    colorHue: 50
  },
  {
    id: "t32",
    title: "The Way You Look Tonight",
    artist: "Frank Sinatra",
    album: "Sinatra Sings Days of Wine and Roses",
    cover: COVERS[1],
    duration: 201,
    year: 1964,
    genre: "Jazz",
    bpm: 133,
    key: "Eb Major",
    energy: 4,
    moods: ["Romantique", "Élégant"],
    momentTags: ["Ouverture du Bal", "Dîner"],
    colorHue: 25
  },
  {
    id: "t33",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
    cover: COVERS[2],
    duration: 270,
    year: 2014,
    genre: "Funk",
    bpm: 115,
    key: "D Minor",
    energy: 9,
    moods: ["Cool", "Dansant"],
    momentTags: ["Dancefloor - Généraliste", "Bal"],
    colorHue: 320
  },
  {
    id: "t34",
    title: "L'Amour Toujours",
    artist: "Gigi D'Agostino",
    album: "L'Amour Toujours",
    cover: COVERS[3],
    duration: 240,
    year: 1999,
    genre: "Eurodance",
    bpm: 130,
    key: "G Minor",
    energy: 9,
    moods: ["Nostalgique", "Énergique"],
    momentTags: ["Dancefloor - Électronique", "Fin de Nuit"],
    colorHue: 150
  },
  {
    id: "t35",
    title: "What A Wonderful World",
    artist: "Louis Armstrong",
    album: "What a Wonderful World",
    cover: COVERS[4],
    duration: 139,
    year: 1967,
    genre: "Jazz",
    bpm: 72,
    key: "F Major",
    energy: 2,
    moods: ["Paisible", "Émouvant"],
    momentTags: ["Dernière chanson", "Cérémonie"],
    colorHue: 100
  }
];

export const MOCK_TIMELINE: Moment[] = [
  { id: "m1", title: "Accueil", time: "14:00", duration: 90, expectedEnergy: 4, tracks: [MOCK_LIBRARY[7], MOCK_LIBRARY[27]], notes: "Ambiance douce et chaleureuse pour l'arrivée des invités." },
  { id: "m2", title: "Cérémonie", time: "15:30", duration: 60, expectedEnergy: 3, tracks: [MOCK_LIBRARY[0], MOCK_LIBRARY[4], MOCK_LIBRARY[10]], notes: "Musique classique et émotionnelle." },
  { id: "m3", title: "Cocktail", time: "17:00", duration: 180, expectedEnergy: 6, tracks: [MOCK_LIBRARY[2], MOCK_LIBRARY[8], MOCK_LIBRARY[12]], notes: "Jazz, soul, musique rythmée mais pas envahissante." },
  { id: "m4", title: "Dîner", time: "20:00", duration: 150, expectedEnergy: 5, tracks: [MOCK_LIBRARY[19], MOCK_LIBRARY[31]], notes: "Volume réduit, discussions." },
  { id: "m5", title: "Bal", time: "22:30", duration: 30, expectedEnergy: 8, tracks: [MOCK_LIBRARY[14]], notes: "Ouverture du bal. Attention à la transition !" },
  { id: "m6", title: "Dancefloor", time: "23:00", duration: 300, expectedEnergy: 9, tracks: [MOCK_LIBRARY[1], MOCK_LIBRARY[3], MOCK_LIBRARY[5], MOCK_LIBRARY[9], MOCK_LIBRARY[11]], notes: "Mix généraliste puis crescendo électronique." },
  { id: "m7", title: "Dernière chanson", time: "04:00", duration: 15, expectedEnergy: 2, tracks: [MOCK_LIBRARY[34], MOCK_LIBRARY[24]], notes: "On redescend doucement." }
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: "p1",
    name: "Cérémonie : Les Incontournables",
    description: "Une sélection de titres romantiques pour accompagner l'engagement.",
    type: "collection",
    tracks: [MOCK_LIBRARY[0], MOCK_LIBRARY[4], MOCK_LIBRARY[10], MOCK_LIBRARY[22]],
    cover: COVERS[0]
  },
  {
    id: "p2",
    name: "Set Cocktail : Sunset",
    description: "Un set fluide mixant soul, jazz et pop solaire.",
    type: "dj-set",
    tracks: [MOCK_LIBRARY[2], MOCK_LIBRARY[8], MOCK_LIBRARY[12], MOCK_LIBRARY[15]],
    cover: COVERS[1]
  },
  {
    id: "p3",
    name: "Peak Time : Dancefloor",
    description: "Les bangers qui mettent tout le monde d'accord.",
    type: "collection",
    tracks: [MOCK_LIBRARY[1], MOCK_LIBRARY[3], MOCK_LIBRARY[5], MOCK_LIBRARY[11], MOCK_LIBRARY[17]],
    cover: COVERS[3]
  }
];

export const MOCK_FOLDERS: Folder[] = [
  {
    id: "f1",
    name: "Inspirations",
    playlistIds: ["p1", "p3"]
  },
  {
    id: "f2",
    name: "Sets préparés",
    playlistIds: ["p2"]
  }
];

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: "prop1",
    guestName: "Alice & Thomas",
    message: "Pour l'ouverture du bal, cette chanson compte tellement pour nous !",
    track: MOCK_LIBRARY[14],
    status: "proposed",
    votes: 3
  },
  {
    id: "prop2",
    guestName: "Oncle Jean",
    message: "Un classique indémodable pour faire danser les jeunes et les moins jeunes.",
    track: MOCK_LIBRARY[11],
    status: "approved",
    votes: 12
  },
  {
    id: "prop3",
    guestName: "Les témoins",
    message: "Pendant le cocktail, ambiance chill indispensable.",
    track: MOCK_LIBRARY[2],
    status: "proposed",
    votes: 5
  }
];
